services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app 
    entrypoint: pnpm dev --host
    ports:
      - 5173:5173
    user: 1000:1000
  api:
    build:
      context: ../api
      dockerfile: ../api/Dockerfile.dev
    volumes:
      - ../api:/app
    environment:
      - DATA_DIR=/app/data_dev
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres?sslmode=disable
    entrypoint: uv --no-cache run uvicorn tso_api.main:app --reload --host 0.0.0.0 --app-dir src
    ports:
      - 3000:300
    user: 1000:1000
    depends_on:
     - db
  db:
    image: postgres:17
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy 
    command: --cookie-name tso_session --pass-authorization-header --upstream http://api:8000/api/ --http-address=:4180 --email-domain '*' --oidc-extra-audience="tso-api" --cookie-refresh=200s
    env_file: 
      - .oauth2.env

